context:
  name: brev
  version: "0.6.312"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/brevdev/brev-cli/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 265ef0698aa8d6b9fd7311b5aa16e2e0a2274dd4a2f3f01f1a035250825b8724

build:
  number: 0
  skip:
    - win
  script:
    - go-licenses save --save_path $SRC_DIR/library_licenses .
    - GOOS="${GOOS}" GOARCH="${GOARCH}" go build -ldflags="-s -w -X github.com/brevdev/brev-cli/brev-cli.Version=${{ version }}" -v -o ${PREFIX}/bin/brev
    # Default to no cross-compile
    - export BREV="${PREFIX}/bin/brev"
    - if: unix and target_platform != build_platform
      then:
        # Need to compile for the build_platform arch
        - if: build_platform == "linux-64" or build_platform == "osx-64"
          # Fail if build_platform changes in future to non-x86_64 arch
          then: export GOARCH=amd64
        - GOOS="${GOOS}" GOARCH="${GOARCH}" go build -ldflags="-s -w -X github.com/brevdev/brev-cli/brev-cli.Version=${{ version }}" -v -o ${BUILD_PREFIX}/bin/brev
        - export BREV="${BUILD_PREFIX}/bin/brev"

    # Install bash, zsh, and fish completions
    - mkdir -p ${PREFIX}/share/bash-completion/completions
    - ${BREV} completion bash > ${PREFIX}/share/bash-completion/completions/brev
    - mkdir -p ${PREFIX}/share/zsh/site-functions
    - ${BREV} completion zsh > ${PREFIX}/share/zsh/site-functions/_brev
    - mkdir -p ${PREFIX}/share/fish/vendor_completions.d
    - ${BREV} completion fish > ${PREFIX}/share/fish/vendor_completions.d/brev.fish

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - package_contents:
      strict: true
      files:
        - bin/brev
        - share/bash-completion/completions/brev
        - share/zsh/site-functions/_brev
        - share/fish/vendor_completions.d/brev.fish

  - script:
      - brev --version
      - brev --help

about:
  homepage: https://developer.nvidia.com/brev
  summary: 'Brev CLI'
  description: |
    CLI tool for managing workspaces provided by brev.dev
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/**/**/LICENSE*
    - library_licenses/**/**/NOTICE*
  documentation: https://docs.nvidia.com/brev/latest/getting-started.html
  repository: https://github.com/brevdev/brev-cli

extra:
  recipe-maintainers:
    - ruben-arts
