context:
  version: "0.6.326"

package:
  name: brev
  version: ${{ version }}

source:
  url: https://github.com/brevdev/brev-cli/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 582aa4307abefe7914f3988fadd28d059fbd14977fa5c90cbe4a45dba66e3aff

build:
  number: 0
  skip:
    - win
  script:
    # go-nvml uses dlopen/dlsym to resolve NVML symbols at runtime. On systems
    # without NVIDIA drivers, go-nvml detects the missing library and gracefully
    # degrades without calling the NVML functions. Set '-z lazy' linker flag to
    # ensure the symbols are only resolved when actually called, allowing for use
    # without NVIDIA drivers.
    # c.f. https://sourceware.org/binutils/docs/ld/Options.html
    - export CGO_LDFLAGS="${CGO_LDFLAGS} -Wl,-z,lazy"

    # Set the plt compiler flag to ensure a Procedure Linkage Table (PLT) for
    # indirect function calls. The alternative is the default for conda-forge's c-compiler
    # flags, of -fno-plt which uses a Global Offset Table (GOT). This would lead
    # to R_*_GLOB_DAT symbols that are always resolved eagerly at load time, even
    # if '-Wl,-z,lazy' is used. As go-nvml uses dlopen/dlsym to resolve NVML
    # symbols at runtime, the PLT is necessary to allow lazy binding of these
    # symbols with '-Wl,-z,lazy'.
    # c.f. https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#index-fno-plt
    - export CGO_CFLAGS="${CGO_CFLAGS} -fplt"

    - go-licenses save --save_path $SRC_DIR/library_licenses . --ignore="buf.build/gen/go/brevdev/protoc-gen-gotag/protocolbuffers/go/tagger"
    - GOOS="${GOOS}" GOARCH="${GOARCH}" go build -ldflags="-s -w -X github.com/brevdev/brev-cli/pkg/cmd/version.Version=v${{ version }}" -v -o ${PREFIX}/bin/brev
    # Default to no cross-compile
    - export BREV="${PREFIX}/bin/brev"
    - if: unix and target_platform != build_platform
      then:
        # Need to compile for the build_platform arch
        - if: build_platform == "linux-64" or build_platform == "osx-64"
          # Fail if build_platform changes in future to non-x86_64 arch
          then: export GOARCH=amd64
        # For cross-compiling, override CONDA_BUILD_SYSROOT to point to the
        # sysroot for the build platform (x86-64), and use the appropriate CC
        # for the build platform ($CC_FOR_BUILD) to compile against the correct
        # headers.
        - CONDA_BUILD_SYSROOT="${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot" CC="${CC_FOR_BUILD}" GOOS="${GOOS}" GOARCH="${GOARCH}" go build -ldflags="-s -w -X github.com/brevdev/brev-cli/pkg/cmd/version.Version=v${{ version }}" -v -o ${BUILD_PREFIX}/bin/brev
        - export BREV="${BUILD_PREFIX}/bin/brev"

    # Install bash, zsh, and fish completions
    - mkdir -p ${PREFIX}/share/bash-completion/completions
    - ${BREV} completion bash > ${PREFIX}/share/bash-completion/completions/brev
    - mkdir -p ${PREFIX}/share/zsh/site-functions
    - ${BREV} completion zsh > ${PREFIX}/share/zsh/site-functions/_brev
    - mkdir -p ${PREFIX}/share/fish/vendor_completions.d
    - ${BREV} completion fish > ${PREFIX}/share/fish/vendor_completions.d/brev.fish

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("go-cgo") }}
    - go-licenses

tests:
  - package_contents:
      strict: true
      files:
        - bin/brev
        - share/bash-completion/completions/brev
        - share/zsh/site-functions/_brev
        - share/fish/vendor_completions.d/brev.fish

  - script:
      - brev --version
      - brev --help

about:
  homepage: https://docs.nvidia.com/brev/
  summary: 'Brev CLI'
  description: |
    CLI tool for managing workspaces provided by brev.nvidia.com
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/**/**/LICENSE*
    - library_licenses/**/**/NOTICE*
  documentation: https://docs.nvidia.com/brev/
  repository: https://github.com/brevdev/brev-cli

extra:
  recipe-maintainers:
    - ruben-arts
    - matthewfeickert
